rate/line_graph/urls.py
from django.conf.urls import url
from line_graph import views

app_name = 'line_graph'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^graph/', views.graph, name='graph'),
    url(r'^add/$', views.edit, name='add'),
    url(r'^edit/(?P<id>\d+)/$', views.edit, name='edit'),
    url(r'^delete/(?P<id>\d+)/$', views.delete, name='delete'),
]

rate/rate/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.conf.urls import include


urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^line_graph/', include('line_graph.urls'), name='line_graph'),
]

rate/line_graph/models.py
from django.db import models


# Create your models here.
class RateData(models.Model):
    id = models.AutoField(primary_key=True)
    rate = models.FloatField(null=False, blank=False)
    datetime = models.DateTimeField(blank=False)

    def __str__(self):
        return str(self.rate)

rate/line_graph/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
import datetime

from plotly import graph_objs
from plotly import offline

from line_graph.models import RateData
from line_graph.form import RateDataForm


def index(request):
    line_graph_data = RateData.objects.order_by('datetime', 'rate', 'id')

    rate_dict = {'line_graph_data': line_graph_data}
    return render(request, 'line_graph/index.html', context=rate_dict)


def edit(request, id=None):
    if id:
        ratedata = get_object_or_404(RateData, pk=id)
    else:
        ratedata = RateData()

    if request.method == 'POST':

        form = RateDataForm(request.POST, instance=ratedata)
        if form.is_valid():
            ratedata = form.save(commit=False)
            ratedata.save()
            return redirect('line_graph:index')
    else:
        form = RateDataForm(instance=ratedata)

    return render(request, 'line_graph/edit.html', dict(form=form, id=id))


def delete(request, id=None):
    ratedata = get_object_or_404(RateData, pk=id)
    ratedata.delete()
    return redirect('line_graph:index')


def graph(request):
    line_graph_data = RateData.objects.order_by('datetime', 'rate')

    rate_dict = {'line_graph_data': line_graph_data}
    create_rate_line_graph(rate_dict)
    return render(request, 'line_graph/graph.html', context=rate_dict)


def create_rate_line_graph(rate_lists_dic):
    """
    Create rate graph as html file

    :param rate_lists [django.db.models.query.QuerySet]: treatRateData model class's data
    """
    date = []
    rate = []

    for acc in rate_lists_dic['line_graph_data']:
        date.append(acc.datetime)
        rate.append(acc.rate)

    line_data = graph_objs.Scatter(
        x=date,
        y=rate
    )
    data = [line_data]

    layout = graph_objs.Layout(
        title="Daily Rate JPY to CAD",
        xaxis={"title": "Datetime"},
        yaxis={"title": "Rate"},
        width=590,
        height=395,
    )

    fig = graph_objs.Figure(data=data, layout=layout)
    offline.plot(fig, filename='./static/html/rate_line_graph', auto_open=False, show_link=False)


def get_data():
    pass

rate/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title>{% block title %}rate{% endblock %}</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300|Roboto+Mono:300,500|Roboto+Slab:300" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static "/css/style.css" %}" />

</head>
<body>

    <div class="container">
      {% block content %}{% endblock %}
    </div>

    <footer>©2018 Ryo Togashi.</footer>

    {% block script %}
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% endblock %}

</body>
</html>

rate/templates/line_graph/edit.html
{% extends "base.html" %}

{% block title %}Edit{% endblock title %}

{% block content %}
    {% if id %}
        <h3 class="page-header">Edit</h3>
        <form action="{% url 'line_graph:edit' id=id %}" method="post" class="form-horizontal" role="form">
    {% else %}
        <h3 class="page-header">Add</h3>
        <form action="{% url 'line_graph:add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      {{ form }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">Submit</button>
          <a href="{% url 'line_graph:index' %}" class="btn btn-primary btn-sm">Back</a>
        </div>
      </div>
    </form>
{% endblock content %}

rate/templates/line_graph/graph.html
{% extends "base.html" %}

{% block title %}
Rate
{% endblock title %}

{% block content %}
<h3>Rate</h3>
<div class="container">
    <a class="btn btn-primary btn-sm" href="#">Get Rate</a>
    <a class="btn btn-primary btn-sm" href="{% url 'line_graph:index' %}">Data</a>
    <div class="blank-bit"></div>
    <div class="clear-fix">
        {% if line_graph_data %}
            <table class="table table-bordered table-condensed table-hover graph-frame">
                <thead>
                    <tr>
                        <th>date</th>
                        <th>time</th>
                        <th>rate</th>
                    </tr>
                </thead>
                {% for acc in line_graph_data %}
                    <tr>
                        <td>{{ acc.datetime.date }}</td>
                        <td>{{ acc.datetime.time }}</td>
                        <td>{{ acc.rate }}</td>
                    </tr>
                {% endfor %}
            </table>
            <iframe class="graph" src="/static/html/rate_line_graph.html"></iframe>
        {% else %}
            <h1>There is no date.</h1>
        {% endif %}
    </div>
</div>

{% endblock content %}
{% block script %}
{% endblock %}

rate/templates/line_graph/index.html
{% extends "base.html" %}

{% block title %}Rate{% endblock title %}

{% block content %}

    <h3>Rate</h3>

    <div class="container">
        {% if line_graph_data %}
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Rate</th>
                        <th>Datetime</th>
                        <th>
                            <a href="{% url 'line_graph:add' %}" class="btn btn-primary btn-sm">Add</a>
                            <a href="{% url 'line_graph:graph' %}" class="btn btn-primary btn-sm">graph</a>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for rate_list in line_graph_data %}
                    <tr>
                        <td>{{ rate_list.rate }}</td>
                        <td>{{ rate_list.datetime }}</td>
                        <td>
                            <a href="{% url 'line_graph:edit' id=rate_list.id %}" class="btn btn-primary btn-sm">Edit</a>
                            <a href="{% url 'line_graph:delete' id=rate_list.id %}" class="btn btn-primary btn-sm" id="btn_del">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <h3>There is no date.</h3>
        {% endif %}
    </div>

{% endblock content %}